import { parseJson, toPgBoolean, toPgDate, toTitleCase } from "@/config/helper-functions";
import { ColumnMeta, TableMetaMap, UploadMetaMap } from "@/config/helper-types";
import type { UploadConfig } from "@/stores/useUploadConfigStore";
import { PublicTableName, PublicTableOrViewName, Row, isTableName } from "@/hooks/database";
import { removeSubnet } from "@/hooks/database/excel-queries/excel-helpers";

export const UPLOAD_TABLE_META: UploadMetaMap = {
  employees: {
    uploadType: "upsert",
    conflictColumn: "employee_pers_no",
    isUploadEnabled: true,
  },
  user_profiles: {
    uploadType: "upsert",
    conflictColumn: "id",
    isUploadEnabled: true,
  },
  lookup_types: {
    uploadType: "upsert",
    conflictColumn: "id",
    isUploadEnabled: true,
  },
  rings: { uploadType: "upsert", conflictColumn: "id", isUploadEnabled: true },
  employee_designations: {
    uploadType: "upsert",
    conflictColumn: "id",
    isUploadEnabled: true,
  },
  maintenance_areas: {
    uploadType: "upsert",
    conflictColumn: "id",
    isUploadEnabled: true,
  },
  ofc_cables: {
    uploadType: "upsert",
    conflictColumn: "id",
    isUploadEnabled: true,
  },
  ofc_connections: {
    uploadType: "upsert",
    conflictColumn: "id",
    isUploadEnabled: true,
  },
  nodes: { uploadType: "upsert", conflictColumn: "id", isUploadEnabled: true },
  systems: {
    uploadType: "upsert",
    conflictColumn: "id",
    isUploadEnabled: false,
  },
  ports_management: {
    uploadType: "upsert",
    conflictColumn: "system_id,port",
    isUploadEnabled: true,
  },
  diary_notes: {
    uploadType: "upsert",
    conflictColumn: "user_id,note_date",
    isUploadEnabled: true,
  },
  inventory_items: {
    uploadType: "upsert",
    conflictColumn: "id",
    isUploadEnabled: true,
  },
  files: {
    uploadType: "upsert",
    conflictColumn: "id",
    isUploadEnabled: true,
  },
  folders: {
    uploadType: "upsert",
    conflictColumn: "id",
    isUploadEnabled: true,
  },
  services: {
    uploadType: "upsert",
    conflictColumn: "id",
    isUploadEnabled: true,
  },
};

export const TABLE_COLUMN_META: TableMetaMap = {
  employees: {
    employee_dob: {
      title: "Employee DOB",
      excelHeader: "Employee DOB",
      transform: toPgDate,
      excelFormat: "date",
    },
    employee_doj: {
      title: "Employee DOJ",
      excelHeader: "Employee DOJ",
      transform: toPgDate,
      excelFormat: "date",
    },
    status: { title: "Status", excelHeader: "Status", transform: toPgBoolean },
  },
  lookup_types: {
    status: { transform: toPgBoolean },
    is_system_default: { transform: toPgBoolean },
  },
  rings: { status: { transform: toPgBoolean } },
  user_profiles: {
    date_of_birth: { transform: toPgDate, excelFormat: "date" },
  },
  ofc_cables: {
    commissioned_on: { transform: toPgDate, excelFormat: "date" },
    status: { transform: toPgBoolean },
  },
  ofc_connections: {
    en_dom: { transform: toPgDate, excelFormat: "date" },
    sn_dom: { transform: toPgDate, excelFormat: "date" },
    status: { transform: toPgBoolean },
    updated_fiber_no_sn: { excelFormat: "integer" },
    updated_fiber_no_en: { excelFormat: "integer" },
    updated_sn_id: { excelFormat: "text" },
    updated_en_id: { excelFormat: "text" },
  },
  nodes: { status: { transform: toPgBoolean } },
  // THE FIX: Added ip_address transform to base systems table
  systems: {
    commissioned_on: { transform: toPgDate, excelFormat: "date" },
    status: { transform: toPgBoolean },
    ip_address: { transform: removeSubnet }, 
  },
  ports_management: {
    port_utilization: { title: "Utilized", transform: toPgBoolean },
    port_admin_status: { title: "Admin Status", transform: toPgBoolean },
    services_count: { title: "Services Count", excelFormat: "integer" }
  },
  // THE FIX: Added sn_ip and en_ip transforms
  v_system_connections_complete: {
    commissioned_on: { transform: toPgDate, excelFormat: "date" },
    status: { transform: toPgBoolean },
    sn_ip: { transform: removeSubnet },
    en_ip: { transform: removeSubnet },
  },
  // THE FIX: Added ip_address transform to the systems view
  v_systems_complete: {
    commissioned_on: { transform: toPgDate, excelFormat: "date" },
    status: { transform: toPgBoolean },
    ip_address: { transform: removeSubnet },
  },
  diary_notes: {
    note_date: { transform: toPgDate, excelFormat: "date" },
    // THE FIX: Parse tags string "[]" into actual Array
    tags: { transform: parseJson, excelFormat: "json" },
  },
  v_audit_logs: {
    created_at: { transform: toPgDate, excelFormat: "date" },
    old_data: { excelFormat: "json" },
    new_data: { excelFormat: "json" },
  },
   // ADDED: Metadata formatting for files
  files: {
    uploaded_at: { transform: toPgDate, excelFormat: "date" },
    file_size: { title: "Size (Bytes)", excelFormat: "number" },
  },
  folders: {
    created_at: { transform: toPgDate, excelFormat: "date" },
    name: { title: "Folder Name" }
  },
  services: {
    created_at: { transform: toPgDate, excelFormat: "date" },
    status: { transform: toPgBoolean },
  },
  v_services: {
    created_at: { transform: toPgDate, excelFormat: "date" },
    status: { transform: toPgBoolean },
    node_name: { title: "Node Location" },
    link_type_name: { title: "Link Type" },
  },
  v_e_files_extended: {
     created_at: { title: "Created At", transform: toPgDate, excelFormat: "date" },
     updated_at: { title: "Last Updated", transform: toPgDate, excelFormat: "date" },
     file_number: { title: "File Number" },
     subject: { title: "Subject" },
     description: { title: "Description" },
     category: { title: "Category" },
     priority: { title: "Priority" },
     initiator_name: { title: "Initiator" },
     current_holder_name: { title: "Current Holder" }, // Matches the import mapping key
     status: { title: "Status" },
     // Hide ID columns to clean up the export
     id: { excelFormat: "text" }, 
     initiator_employee_id: { title: "Initiator ID" },
     current_holder_employee_id: { title: "Holder ID" },
  },
  v_inventory_items: {
      last_issued_to: { title: "Last Issued To (History)" },
      last_issue_reason: { title: "Last Issue Reason (History)" },
      last_issued_date: { title: "Last Issue Date (History)", transform: toPgDate, excelFormat: "date" },
      cost: { title: "Unit Cost" },
      total_value: { title: "Total Value (Calculated)" },
      
      // ADDED: Virtual columns for Import Mapping
      // These keys don't exist in the view, but we add them here so the importer can recognize them
      // if the user adds them to the Excel file manually for bulk actions.
      // Note: The useInventoryExcelUpload hook handles the mapping manually, but this helps consistency.
  }
};

export function buildColumnConfig<T extends PublicTableOrViewName>(tableName: T) {
  const keys = TABLE_COLUMN_KEYS[
    tableName as keyof typeof TABLE_COLUMN_KEYS
  ] as unknown as readonly (keyof Row<T> & string)[];
  const meta = (TABLE_COLUMN_META[tableName as keyof typeof TABLE_COLUMN_META] || {}) as Record<
    string,
    ColumnMeta
  >;
  return keys.map((key) => {
    const m = meta[key] || {};
    const title = m.title ?? toTitleCase(key);
    // THE FIX: Ensure 'transform' is passed to the returned config
    return { key, dataIndex: key, title, excelFormat: m.excelFormat, transform: m.transform };
  });
}
export function buildUploadConfig<T extends PublicTableOrViewName>(tableName: T) {
  type RowType = Row<T>;
  type ColumnKey = keyof RowType & string;
  const tableColumnKeys = TABLE_COLUMN_KEYS as Record<string, readonly string[]>;
  const keys = (tableColumnKeys[tableName] || []) as readonly ColumnKey[];
  const meta = (TABLE_COLUMN_META[tableName as keyof typeof TABLE_COLUMN_META] || {}) as Partial<
    Record<ColumnKey, ColumnMeta>
  >;

  const tableMeta = isTableName(tableName)
    ? UPLOAD_TABLE_META[tableName as PublicTableName]
    : undefined;

  const uploadType = tableMeta?.uploadType ?? "upsert";
  const conflictColumn = tableMeta?.conflictColumn;
  const isUploadEnabled = tableMeta?.isUploadEnabled ?? true;

  const columnMapping = keys.map((key) => {
    const m = meta[key] || {};
    const excelHeader = m.excelHeader ?? toTitleCase(key);
    let transform = m.transform;
    if (!transform) {
      const k = String(key).toLowerCase();
      if (k.endsWith("_at") || k.endsWith("_on") || k.includes("date")) {
        transform = toPgDate;
      } else if (
        k.startsWith("is_") ||
        k.startsWith("has_") ||
        k.startsWith("can_") ||
        k.includes("enabled") ||
        k.includes("active") ||
        k === "status"
      ) {
        transform = toPgBoolean;
      }
    }
    return { excelHeader, dbKey: key, transform };
  });

  return {
    tableName,
    columnMapping,
    uploadType,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    conflictColumn: conflictColumn as any,
    isUploadEnabled,
  } satisfies UploadConfig<T>;
}

export type ValidatedColumnKeys = {
  [T in PublicTableOrViewName]: { [K in keyof Row<T>]: K };
};

const TABLE_COLUMN_OBJECTS = {
  // ==================== Core Tables ====================
  user_profiles: {
    id: "id",
    first_name: "first_name",
    last_name: "last_name",
    phone_number: "phone_number",
    role: "role",
    designation: "designation",
    status: "status",
    avatar_url: "avatar_url",
    date_of_birth: "date_of_birth",
    address: "address",
    preferences: "preferences",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  lookup_types: {
    id: "id",
    category: "category",
    name: "name",
    code: "code",
    description: "description",
    sort_order: "sort_order",
    is_system_default: "is_system_default",
    is_ring_based: "is_ring_based",
    status: "status",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  maintenance_areas: {
    id: "id",
    name: "name",
    contact_person: "contact_person",
    contact_number: "contact_number",
    email: "email",
    latitude: "latitude",
    longitude: "longitude",
    address: "address",
    code: "code",
    status: "status",
    area_type_id: "area_type_id",
    parent_id: "parent_id",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  employee_designations: {
    id: "id",
    name: "name",
    parent_id: "parent_id",
    status: "status",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  employees: {
    id: "id",
    employee_pers_no: "employee_pers_no",
    employee_name: "employee_name",
    employee_email: "employee_email",
    employee_dob: "employee_dob",
    employee_doj: "employee_doj",
    employee_contact: "employee_contact",
    employee_addr: "employee_addr",
    employee_designation_id: "employee_designation_id",
    maintenance_terminal_id: "maintenance_terminal_id",
    status: "status",
    remark: "remark",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  rings: {
    id: "id",
    name: "name",
    total_nodes: "total_nodes",
    description: "description",
    ring_type_id: "ring_type_id",
    maintenance_terminal_id: "maintenance_terminal_id",
    bts_status: "bts_status",
    ofc_status: "ofc_status",
    spec_status: "spec_status",
    is_closed_loop: "is_closed_loop",
    topology_config: "topology_config",
    status: "status",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  nodes: {
    id: "id",
    name: "name",
    node_type_id: "node_type_id",
    maintenance_terminal_id: "maintenance_terminal_id",
    latitude: "latitude",
    longitude: "longitude",
    status: "status",
    remark: "remark",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  ofc_cables: {
    id: "id",
    route_name: "route_name",
    capacity: "capacity",
    ofc_type_id: "ofc_type_id",
    transnet_id: "transnet_id",
    transnet_rkm: "transnet_rkm",
    current_rkm: "current_rkm",
    ofc_owner_id: "ofc_owner_id",
    asset_no: "asset_no",
    maintenance_terminal_id: "maintenance_terminal_id",
    commissioned_on: "commissioned_on",
    remark: "remark",
    sn_id: "sn_id",
    en_id: "en_id",
    status: "status",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  files: {
    id: "id",
    file_name: "file_name",
    file_route: "file_route",
    file_size: "file_size",
    file_type: "file_type",
    file_url: "file_url",
    folder_id: "folder_id",
    uploaded_at: "uploaded_at",
    user_id: "user_id",
  },
  folders: {
    id: "id",
    name: "name",
    user_id: "user_id",
    created_at: "created_at",
  },
  user_activity_logs: {
    action_type: "action_type",
    created_at: "created_at",
    details: "details",
    id: "id",
    new_data: "new_data",
    old_data: "old_data",
    record_id: "record_id",
    table_name: "table_name",
    user_id: "user_id",
    user_role: "user_role",
  },
  e_files: {
    category: "category",
    created_at: "created_at",
    current_holder_employee_id: "current_holder_employee_id",
    description: "description",
    file_number: "file_number",
    initiator_employee_id: "initiator_employee_id",
    priority: "priority",
    recorded_by_user_id: "recorded_by_user_id",
    status: "status",
    subject: "subject",
    updated_at: "updated_at",
    id: "id",
  },
  

  // ==================== System Tables ====================
  systems: {
    id: "id",
    system_name: "system_name",

    s_no: "s_no",
    node_id: "node_id",
    system_type_id: "system_type_id",
    maan_node_id: "maan_node_id",
    ip_address: "ip_address",
    maintenance_terminal_id: "maintenance_terminal_id",
    commissioned_on: "commissioned_on",
    status: "status",
    remark: "remark",
    created_at: "created_at",
    updated_at: "updated_at",
    make: "make",
    is_hub: "is_hub",
    system_capacity_id: "system_capacity_id",
  },
  system_connections: {
    bandwidth: "bandwidth",
    commissioned_on: "commissioned_on",
    created_at: "created_at",
    en_id: "en_id",
    en_interface: "en_interface",
    en_ip: "en_ip",
    id: "id",
    media_type_id: "media_type_id",
    protection_fiber_in_ids: "protection_fiber_in_ids",
    protection_fiber_out_ids: "protection_fiber_out_ids",
    remark: "remark",
    service_id: "service_id",
    services_interface: "services_interface",
    services_ip: "services_ip",
    sn_id: "sn_id",
    sn_interface: "sn_interface",
    sn_ip: "sn_ip",
    status: "status",
    system_id: "system_id",
    system_protection_interface: "system_protection_interface",
    system_working_interface: "system_working_interface",
    en_protection_interface: "en_protection_interface",
    updated_at: "updated_at",
    working_fiber_in_ids: "working_fiber_in_ids",
    working_fiber_out_ids: "working_fiber_out_ids",
  },
  services: {
    bandwidth_allocated: "bandwidth_allocated",
    created_at: "created_at",
    description: "description",
    id: "id",
    lc_id: "lc_id",
    link_type_id: "link_type_id",
    name: "name",
    node_id: "node_id",
    end_node_id: "end_node_id",
    status: "status",
    unique_id: "unique_id",
    updated_at: "updated_at",
    vlan: "vlan",
  },
  ports_management: {
    id: "id", // Added primary key
    system_id: "system_id",
    port: "port",
    port_type_id: "port_type_id",
    port_capacity: "port_capacity",
    sfp_serial_no: "sfp_serial_no",
    port_utilization: "port_utilization",
    port_admin_status: "port_admin_status",
    services_count: "services_count",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  ring_based_systems: {
    system_id: "system_id",
    ring_id: "ring_id",
    order_in_ring: "order_in_ring",
    maintenance_area_id: "maintenance_area_id",
  },
  sdh_connections: {
    system_connection_id: "system_connection_id",
    stm_no: "stm_no",
    carrier: "carrier",
    a_slot: "a_slot",
    a_customer: "a_customer",
    b_slot: "b_slot",
    b_customer: "b_customer",
  },
  ofc_connections: {
    id: "id",
    ofc_id: "ofc_id",
    fiber_no_sn: "fiber_no_sn",
    fiber_no_en: "fiber_no_en",
    updated_fiber_no_sn: "updated_fiber_no_sn",
    updated_fiber_no_en: "updated_fiber_no_en",
    updated_sn_id: "updated_sn_id",
    updated_en_id: "updated_en_id",
    otdr_distance_sn_km: "otdr_distance_sn_km",
    sn_dom: "sn_dom",
    sn_power_dbm: "sn_power_dbm",
    system_id: "system_id",
    otdr_distance_en_km: "otdr_distance_en_km",
    en_dom: "en_dom",
    en_power_dbm: "en_power_dbm",
    remark: "remark",
    route_loss_db: "route_loss_db",
    logical_path_id: "logical_path_id",
    fiber_role: "fiber_role",
    path_direction: "path_direction",
    path_segment_order: "path_segment_order",
    source_port: "source_port",
    destination_port: "destination_port",
    connection_category: "connection_category",
    connection_type: "connection_type",
    status: "status",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  cable_segments: {
    id: "id",
    original_cable_id: "original_cable_id",
    segment_order: "segment_order",
    start_node_id: "start_node_id",
    end_node_id: "end_node_id",
    start_node_type: "start_node_type",
    end_node_type: "end_node_type",
    distance_km: "distance_km",
    fiber_count: "fiber_count",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  fiber_splices: {
    id: "id",
    jc_id: "jc_id",
    incoming_segment_id: "incoming_segment_id",
    incoming_fiber_no: "incoming_fiber_no",
    outgoing_segment_id: "outgoing_segment_id",
    outgoing_fiber_no: "outgoing_fiber_no",
    splice_type_id: "splice_type_id",
    logical_path_id: "logical_path_id",
    loss_db: "loss_db",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  junction_closures: {
    id: "id",
    node_id: "node_id",
    ofc_cable_id: "ofc_cable_id",
    position_km: "position_km",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  logical_paths: {
    name: "name",
    source_port: "source_port",
    destination_port: "destination_port",
    status: "status",
    created_at: "created_at",
    updated_at: "updated_at",
    ring_id: "ring_id",
    id: "id",
    start_node_id: "start_node_id",
    source_system_id: "source_system_id",
    end_node_id: "end_node_id",
    destination_system_id: "destination_system_id",
  },
  logical_fiber_paths: {
    id: "id",
    path_name: "path_name",
    working_path_id: "working_path_id",
    path_role: "path_role",
    path_type_id: "path_type_id",
    source_system_id: "source_system_id",
    destination_system_id: "destination_system_id",
    operational_status_id: "operational_status_id",
    source_port: "source_port",
    destination_port: "destination_port",
    total_distance_km: "total_distance_km",
    total_loss_db: "total_loss_db",
    service_type: "service_type",
    bandwidth_gbps: "bandwidth_gbps",
    wavelength_nm: "wavelength_nm",
    commissioned_date: "commissioned_date",
    remark: "remark",
    created_at: "created_at",
    updated_at: "updated_at",
    system_connection_id: "system_connection_id",
  },
  logical_path_segments: {
    id: "id",
    logical_path_id: "logical_path_id",
    ofc_cable_id: "ofc_cable_id",
    path_order: "path_order",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  diary_notes: {
    id: "id",
    user_id: "user_id",
    tags: "tags",
    note_date: "note_date",
    content: "content",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  inventory_items: {
    id: "id",
    asset_no: "asset_no",
    name: "name",
    description: "description",
    category_id: "category_id",
    status_id: "status_id",
    location_id: "location_id",
    functional_location_id: "functional_location_id",
    quantity: "quantity",
    purchase_date: "purchase_date",
    vendor: "vendor",
    cost: "cost",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  inventory_transactions: {
    id: "id",
    inventory_item_id: "inventory_item_id",
    transaction_type: "transaction_type",
    quantity: "quantity",
    unit_cost_at_time: "unit_cost_at_time",
    total_cost_calculated: "total_cost_calculated",
    issued_to: "issued_to",
    issue_reason: "issue_reason",
    issued_date: "issued_date",
    performed_by_user_id: "performed_by_user_id",
    created_at: "created_at",
  },
  
  // ==================== Views ====================
  v_inventory_transactions_extended: {
    asset_no: "asset_no",
    created_at: "created_at",
    id: "id",
    inventory_item_id: "inventory_item_id",
    issue_reason: "issue_reason",
    issued_date: "issued_date",
    issued_to: "issued_to",
    item_name: "item_name",
    performed_by_email: "performed_by_email",
    performed_by_name: "performed_by_name",
    performed_by_user_id: "performed_by_user_id",
    quantity: "quantity",
    total_cost_calculated: "total_cost_calculated",
    transaction_type: "transaction_type",
    unit_cost_at_time: "unit_cost_at_time",
  },
  v_cable_utilization: {
    cable_id: "cable_id",
    route_name: "route_name",
    capacity: "capacity",
    used_fibers: "used_fibers",
    available_fibers: "available_fibers",
    utilization_percent: "utilization_percent",
  },
  v_end_to_end_paths: {
    path_id: "path_id",
    path_name: "path_name",
    source_system_id: "source_system_id",
    destination_system_id: "destination_system_id",
    operational_status: "operational_status",
    segment_count: "segment_count",
    route_names: "route_names",
    total_distance_km: "total_distance_km",
    total_loss_db: "total_loss_db",
  },
  v_ofc_cables_complete: {
    route_name: "route_name",
    capacity: "capacity",
    asset_no: "asset_no",
    transnet_id: "transnet_id",
    transnet_rkm: "transnet_rkm",
    current_rkm: "current_rkm",
    commissioned_on: "commissioned_on",
    remark: "remark",
    ofc_type_name: "ofc_type_name",
    ofc_type_code: "ofc_type_code",
    ofc_owner_name: "ofc_owner_name",
    ofc_owner_code: "ofc_owner_code",
    status: "status",
    sn_name: "sn_name",
    en_name: "en_name",
    sn_node_type_name: "sn_node_type_name",
    en_node_type_name: "en_node_type_name",
    maintenance_area_name: "maintenance_area_name",
    maintenance_area_code: "maintenance_area_code",
    created_at: "created_at",
    updated_at: "updated_at",
    id: "id",
    sn_id: "sn_id",
    en_id: "en_id",
    ofc_type_id: "ofc_type_id",
    ofc_owner_id: "ofc_owner_id",
    maintenance_terminal_id: "maintenance_terminal_id",
  },
  v_nodes_complete: {
    id: "id",
    name: "name",
    latitude: "latitude",
    longitude: "longitude",
    node_type_name: "node_type_name",
    node_type_code: "node_type_code",
    remark: "remark",
    maintenance_area_name: "maintenance_area_name",
    status: "status",
    node_type_id: "node_type_id",
    maintenance_terminal_id: "maintenance_terminal_id",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  v_ofc_connections_complete: {
    id: "id",
    ofc_route_name: "ofc_route_name",
    updated_sn_name: "updated_sn_name",
    updated_fiber_no_sn: "updated_fiber_no_sn",
    otdr_distance_sn_km: "otdr_distance_sn_km",
    sn_power_dbm: "sn_power_dbm",
    sn_dom: "sn_dom",
    updated_en_name: "updated_en_name",
    updated_fiber_no_en: "updated_fiber_no_en",
    otdr_distance_en_km: "otdr_distance_en_km",
    en_power_dbm: "en_power_dbm",
    en_dom: "en_dom",
    route_loss_db: "route_loss_db",
    ofc_type_name: "ofc_type_name",
    system_name: "system_name",
    source_port: "source_port",
    destination_port: "destination_port",
    maintenance_area_name: "maintenance_area_name",
    connection_category: "connection_category",
    connection_type: "connection_type",
    fiber_role: "fiber_role",
    path_direction: "path_direction",
    remark: "remark",
    status: "status",
    sn_name: "sn_name",
    en_name: "en_name",
    fiber_no_sn: "fiber_no_sn",
    fiber_no_en: "fiber_no_en",
    path_segment_order: "path_segment_order",
    updated_at: "updated_at",
    created_at: "created_at",
    logical_path_id: "logical_path_id",
    updated_sn_id: "updated_sn_id",
    updated_en_id: "updated_en_id",
    system_id: "system_id",
    sn_id: "sn_id",
    en_id: "en_id",
    ofc_id: "ofc_id",
  },
  v_system_connections_complete: {
    id: "id",
    system_id: "system_id",
    system_name: "system_name",
    system_type_name: "system_type_name",
    system_working_interface: "system_working_interface",
    service_name: "service_name",
    vlan: "vlan",
    bandwidth_allocated: "bandwidth_allocated",
    sdh_a_customer: "sdh_a_customer",
    sdh_a_slot: "sdh_a_slot",
    sdh_b_customer: "sdh_b_customer",
    sdh_b_slot: "sdh_b_slot",
    sdh_carrier: "sdh_carrier",
    sdh_stm_no: "sdh_stm_no",
    connected_link_type_name: "connected_link_type_name",
    sn_interface: "sn_interface",
    connected_link_type_id: "connected_link_type_id",
    en_interface: "en_interface",
    service_node_id: "service_node_id",
    service_node_name: "service_node_name",
    connected_system_name: "connected_system_name",
    connected_system_type_name: "connected_system_type_name",
    sn_system_type_name: "sn_system_type_name",
    en_system_type_name: "en_system_type_name",
    sn_node_name: "sn_node_name",
    en_node_name: "en_node_name",
    service_end_node_name: "service_end_node_name",
    lc_id: "lc_id",
    sn_name: "sn_name",
    en_name: "en_name",
    unique_id: "unique_id",
    service_id: "service_id",
    services_interface: "services_interface",
    services_ip: "services_ip",
    system_protection_interface: "system_protection_interface",
    en_protection_interface: "en_protection_interface",
    sn_node_id: "sn_node_id",
    en_node_id: "en_node_id",
    service_end_node_id: "service_end_node_id",
    media_type_id: "media_type_id",
    media_type_name: "media_type_name",
    bandwidth: "bandwidth",
    status: "status",
    sn_id: "sn_id",
    en_id: "en_id",
    commissioned_on: "commissioned_on",
    created_at: "created_at",
    en_ip: "en_ip",
    remark: "remark",
    sn_ip: "sn_ip",
    updated_at: "updated_at",
    working_fiber_in_ids: "working_fiber_in_ids",
    working_fiber_out_ids: "working_fiber_out_ids",
    protection_fiber_in_ids: "protection_fiber_in_ids",
    protection_fiber_out_ids: "protection_fiber_out_ids",
  },
  v_systems_complete: {
    system_name: "system_name",
    system_type_code: "system_type_code",
    system_capacity_name: "system_capacity_name",
    node_name: "node_name",
    is_hub: "is_hub",
    ip_address: "ip_address",
    is_ring_based: "is_ring_based",
    order_in_ring: "order_in_ring",
    maan_node_id: "maan_node_id",
    node_type_name: "node_type_name",
    make: "make",
    remark: "remark",
    s_no: "s_no",
    latitude: "latitude",
    longitude: "longitude",
    system_category: "system_category",
    status: "status",
    commissioned_on: "commissioned_on",
    ring_id: "ring_id",
    system_type_id: "system_type_id",
    node_id: "node_id",
    maintenance_terminal_id: "maintenance_terminal_id",
    ring_logical_area_name: "ring_logical_area_name",
    system_maintenance_terminal_name: "system_maintenance_terminal_name",
    system_type_name: "system_type_name",
    ring_associations: "ring_associations",
    updated_at: "updated_at",
    created_at: "created_at",
    system_capacity_id: "system_capacity_id",
    id: "id",
  },
  v_user_profiles_extended: {
    id: "id",
    email: "email",
    full_name: "full_name",
    role: "role",
    status: "status",
    last_sign_in_at: "last_sign_in_at",
    is_email_verified: "is_email_verified",
    created_at: "created_at",
    updated_at: "updated_at",
    account_age_days: "account_age_days",
    address: "address",
    auth_updated_at: "auth_updated_at",
    avatar_url: "avatar_url",
    computed_status: "computed_status",
    date_of_birth: "date_of_birth",
    designation: "designation",
    email_confirmed_at: "email_confirmed_at",
    first_name: "first_name",
    is_phone_verified: "is_phone_verified",
    is_super_admin: "is_super_admin",
    last_activity_period: "last_activity_period",
    last_name: "last_name",
    phone_confirmed_at: "phone_confirmed_at",
    phone_number: "phone_number",
    preferences: "preferences",
    raw_app_meta_data: "raw_app_meta_data",
    raw_user_meta_data: "raw_user_meta_data",
  },
  v_lookup_types: {
    id: "id",
    category: "category",
    name: "name",
    code: "code",
    description: "description",
    sort_order: "sort_order",
    status: "status",
    is_system_default: "is_system_default",
    is_ring_based: "is_ring_based",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  v_employee_designations: {
    id: "id",
    name: "name",
    parent_id: "parent_id",
    status: "status",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  v_maintenance_areas: {
    id: "id",
    code: "code",
    name: "name",
    address: "address",
    email: "email",
    contact_person: "contact_person",
    contact_number: "contact_number",
    latitude: "latitude",
    longitude: "longitude",
    area_type_id: "area_type_id",
    parent_id: "parent_id",
    status: "status",
    created_at: "created_at",
    updated_at: "updated_at",
    maintenance_area_type_name: "maintenance_area_type_name",
    maintenance_area_type_code: "maintenance_area_type_code",
  },
  v_employees: {
    id: "id",
    employee_name: "employee_name",
    employee_contact: "employee_contact",
    employee_email: "employee_email",
    employee_pers_no: "employee_pers_no",
    employee_designation_name: "employee_designation_name",
    employee_dob: "employee_dob",
    employee_doj: "employee_doj",
    employee_addr: "employee_addr",
    maintenance_area_name: "maintenance_area_name",
    employee_designation_id: "employee_designation_id",
    maintenance_terminal_id: "maintenance_terminal_id",
    remark: "remark",
    status: "status",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  v_rings: {
    id: "id",
    name: "name",
    total_nodes: "total_nodes",
    description: "description",
    ring_type_name: "ring_type_name",
    ring_type_code: "ring_type_code",
    maintenance_area_name: "maintenance_area_name",
    is_closed_loop: "is_closed_loop",
    topology_config: "topology_config",
    bts_status: "bts_status",
    ofc_status: "ofc_status",
    spec_status: "spec_status",
    status: "status",
    created_at: "created_at",
    updated_at: "updated_at",
    maintenance_terminal_id: "maintenance_terminal_id",
    ring_type_id: "ring_type_id",
  },
  file_movements: {
    action_type: "action_type",
    created_at: "created_at",
    file_id: "file_id",
    from_employee_id: "from_employee_id",
    performed_by_user_id: "performed_by_user_id",
    remarks: "remarks",
    to_employee_id: "to_employee_id",
    id: "id",
  },
  v_cable_segments_at_jc: {
    end_node_id: "end_node_id",
    fiber_count: "fiber_count",
    id: "id",
    jc_node_id: "jc_node_id",
    original_cable_id: "original_cable_id",
    segment_order: "segment_order",
    start_node_id: "start_node_id",
  },
  v_junction_closures_complete: {
    id: "id",
    latitude: "latitude",
    longitude: "longitude",
    name: "name",
    node_id: "node_id",
    ofc_cable_id: "ofc_cable_id",
    position_km: "position_km",
  },
  v_ring_nodes: {
    system_node_name: "system_node_name",
    system_type_code: "system_type_code",
    id: "id",
    ip: "ip",
    is_hub: "is_hub",
    lat: "lat",
    long: "long",
    name: "name",
    order_in_ring: "order_in_ring",
    remark: "remark",
    ring_id: "ring_id",
    node_id: "node_id",
    system_type: "system_type",
    ring_name: "ring_name",
    ring_status: "ring_status",
    system_status: "system_status",
    type: "type",
  },
  v_inventory_items: {
    asset_no: "asset_no",
    category_id: "category_id",
    category_name: "category_name",
    cost: "cost",
    created_at: "created_at",
    description: "description",
    functional_location: "functional_location",
    functional_location_id: "functional_location_id",
    id: "id",
    last_issue_reason: "last_issue_reason",
    last_issued_date: "last_issued_date",
    last_issued_to: "last_issued_to",
    location_id: "location_id",
    name: "name",
    purchase_date: "purchase_date",
    quantity: "quantity",
    status_id: "status_id",
    status_name: "status_name",
    store_location: "store_location",
    total_value: "total_value",
    updated_at: "updated_at",
    vendor: "vendor",
  },
  v_ports_management_complete: {
    id: "id",
    system_id: "system_id",
    system_name: "system_name",
    port: "port",
    port_type_id: "port_type_id",
    port_type_name: "port_type_name",
    port_type_code: "port_type_code",
    port_capacity: "port_capacity",
    sfp_serial_no: "sfp_serial_no",
    port_utilization: "port_utilization",
    port_admin_status: "port_admin_status",
    services_count: "services_count",
    created_at: "created_at",
    updated_at: "updated_at",
  },
  v_audit_logs: {
    id: "id",
    user_id: "user_id",
    user_role: "user_role",
    action_type: "action_type",
    table_name: "table_name",
    record_id: "record_id",
    old_data: "old_data",
    new_data: "new_data",
    details: "details",
    created_at: "created_at",
    performed_by_name: "performed_by_name",
    performed_by_email: "performed_by_email",
    performed_by_avatar: "performed_by_avatar",
  },
  v_services: {
    name: "name",
    node_name: "node_name",
    end_node_name: "end_node_name",
    link_type_name: "link_type_name",
    bandwidth_allocated: "bandwidth_allocated",
    vlan: "vlan",
    lc_id: "lc_id",
    unique_id: "unique_id",
    description: "description",
    maintenance_area_name: "maintenance_area_name",
    status: "status",
    created_at: "created_at",
    updated_at: "updated_at",
    id: "id",
    node_id: "node_id",
    end_node_id: "end_node_id",
    link_type_id: "link_type_id",
  },
  v_e_files_extended: {
    category: "category",
    created_at: "created_at",
    current_holder_area: "current_holder_area",
    current_holder_designation: "current_holder_designation",
    current_holder_employee_id: "current_holder_employee_id",
    current_holder_name: "current_holder_name",
    description: "description",
    file_number: "file_number",
    initiator_designation: "initiator_designation",
    initiator_employee_id: "initiator_employee_id",
    initiator_name: "initiator_name",
    priority: "priority",
    recorded_by_name: "recorded_by_name",
    recorded_by_user_id: "recorded_by_user_id",
    status: "status",
    subject: "subject",
    updated_at: "updated_at",
    id: "id",
  },
  v_file_movements_extended: {
    action_type: "action_type",
    created_at: "created_at",
    file_id: "file_id",
    from_employee_designation: "from_employee_designation",
    from_employee_id: "from_employee_id",
    from_employee_name: "from_employee_name",
    performed_by_name: "performed_by_name",
    performed_by_user_id: "performed_by_user_id",
    remarks: "remarks",
    to_employee_designation: "to_employee_designation",
    to_employee_id: "to_employee_id",
    to_employee_name: "to_employee_name",
    id: "id",
  }

} satisfies ValidatedColumnKeys;

// Programmatically create the array-based export from the validated object.
export const TABLE_COLUMN_KEYS = (
  Object.keys(TABLE_COLUMN_OBJECTS) as Array<keyof typeof TABLE_COLUMN_OBJECTS>
).reduce((acc, tableName) => {
  const value = TABLE_COLUMN_OBJECTS[tableName];
  acc[tableName] = Object.keys(value) as (keyof Row<typeof tableName>)[];
  return acc;
}, {} as { [K in PublicTableOrViewName]: (keyof Row<K>)[] });

export const TABLES = {
  user_profiles: "user_profiles",
  employees: "employees",
  lookup_types: "lookup_types",
  rings: "rings",
  employee_designations: "employee_designations",
  maintenance_areas: "maintenance_areas",
  ofc_cables: "ofc_cables",
  ofc_connections: "ofc_connections",
  nodes: "nodes",
  systems: "systems",
  sfp_based_connections: "sfp_based_connections",
  management_ports: "management_ports",
  sdh_connections: "sdh_connections",
  sdh_node_associations: "sdh_node_associations",
  sdh_systems: "sdh_systems",
  system_connections: "system_connections",
  files: "files",
  folders: "folders",
  ring_based_systems: "ring_based_systems",
  logical_path_segments: "logical_path_segments",
  logical_fiber_paths: "logical_fiber_paths",
  junction_closures: "junction_closures",
  cable_segments: "cable_segments",
  fiber_splices: "fiber_splices",
  logical_paths: "logical_paths",
  diary_notes: "diary_notes",
  inventory_items: "inventory_items",
  inventory_transactions: "inventory_transactions",
  services: "services",
  e_files: "e_files",
  file_movements: "file_movements",
} as const;

export const VIEWS = {
  v_cable_utilization: "v_cable_utilization",
  v_end_to_end_paths: "v_end_to_end_paths",
  v_nodes_complete: "v_nodes_complete",
  v_ofc_cables_complete: "v_ofc_cables_complete",
  v_ofc_connections_complete: "v_ofc_connections_complete",
  v_system_connections_complete: "v_system_connections_complete",
  v_systems_complete: "v_systems_complete",
  v_user_profiles_extended: "v_user_profiles_extended",
  v_lookup_types: "v_lookup_types",
  v_employee_designations: "v_employee_designations",
  v_maintenance_areas: "v_maintenance_areas",
  v_employees: "v_employees",
  v_rings: "v_rings",
  v_cable_segments_at_jc: "v_cable_segments_at_jc",
  v_junction_closures_complete: "v_junction_closures_complete",
  v_ring_nodes: "v_ring_nodes",
  v_inventory_items: "v_inventory_items",
  v_audit_logs: "v_audit_logs",
  v_services: "v_services",
  v_e_files_extended: "v_e_files_extended",
  v_file_movements_extended: "v_file_movements_extended",
} as const;

export const TABLE_NAMES = {
  ...TABLES,
  ...VIEWS,
} as const;