#!/bin/bash
# Test the automatic cable segmentation trigger system

echo "=== Testing Automatic Cable Segmentation Triggers ==="
echo ""

echo "1. Testing trigger function creation:"
echo "   - Check if trigger_create_cable_segments_on_jc() function exists"
echo "   - Check if trigger_junction_closures_create_segments trigger exists"
echo ""

echo "2. Test the complete flow:"
echo "   a) Insert a new junction closure"
echo "   b) Verify cable segments are created automatically"
echo "   c) Verify fiber connections are created"
echo ""

echo "3. Run these SQL commands in Supabase SQL Editor:"
echo ""

echo "=== TEST 1: Check trigger setup ==="
echo "SELECT trigger_name, event_manipulation, action_timing"
echo "FROM information_schema.triggers"
echo "WHERE event_object_table = 'junction_closures'"
echo "ORDER BY trigger_name;"
echo ""

echo "=== TEST 2: Test automatic segmentation ==="
echo "-- Insert a test junction closure"
echo "INSERT INTO junction_closures (node_id, ofc_cable_id, position_km)"
echo "VALUES ('4d2b0dc9-f63a-4a6d-8fdc-ddb7d44875a7', '117c7353-99a9-4220-8cfd-0669d93b4f4b', 5.0);"
echo ""

echo "=== TEST 3: Verify segments were created ==="
echo "-- Check cable segments"
echo "SELECT id, segment_order, start_node_id, end_node_id, distance_km"
echo "FROM cable_segments"
echo "WHERE original_cable_id = '117c7353-99a9-4220-8cfd-0669d93b4f4b'"
echo "ORDER BY segment_order;"
echo ""

echo "=== TEST 4: Verify fiber connections ==="
echo "-- Check fiber connections"
echo "SELECT cs.id as segment_id, COUNT(oc.id) as fiber_count"
echo "FROM cable_segments cs"
echo "LEFT JOIN ofc_connections oc ON oc.ofc_id = cs.original_cable_id"
echo "WHERE cs.original_cable_id = '117c7353-99a9-4220-8cfd-0669d93b4f4b'"
echo "GROUP BY cs.id;"
echo ""

echo "=== TEST 5: Clean up test data ==="
echo "-- Delete the test JC (this will also delete segments via CASCADE)"
echo "DELETE FROM junction_closures"
echo "WHERE node_id = '4d2b0dc9-f63a-4a6d-8fdc-ddb7d44875a7'"
echo "  AND ofc_cable_id = '117c7353-99a9-4220-8cfd-0669d93b4f4b'"
echo "  AND position_km = 5.0;"
echo ""

echo "=== Expected Results ==="
echo "✅ Trigger function exists: trigger_create_cable_segments_on_jc"
echo "✅ Trigger exists: trigger_junction_closures_create_segments"
echo "✅ New cable segments created automatically"
echo "✅ Fiber connections created for each segment"
echo "✅ Test data cleaned up successfully"
echo ""

echo "=== What happens in your app ==="
echo "1. User opens JC modal and selects a node"
echo "2. User enters position and clicks Save"
echo "3. JcFormModal calls add_junction_closure() function"
echo "4. Database function inserts JC record"
echo "5. Trigger automatically calls create_cable_segments_on_jc_add()"
echo "6. Cable segments are created automatically"
echo "7. User sees success message"
echo ""

echo "=== Debug logs to look for ==="
echo "In browser console:"
echo "- 'JC created: {...}'"
echo "- 'Cable segments will be created automatically by database trigger'"
echo "- 'Junction Closure created! Cable segments will be created automatically.'"
echo ""
echo "In database logs (Supabase dashboard):"
echo "- 'Automatically created cable segments for new JC: ...'"
