#!/bin/bash
# Test JC deletion and automatic segment recreation

echo "=== Testing JC Deletion and Automatic Segment Recreation ==="
echo ""

echo "1. Setup: Create a test JC first"
echo "2. Verify segments are created automatically"
echo "3. Delete the JC"
echo "4. Verify segments are recreated automatically"
echo ""

echo "=== SQL COMMANDS TO RUN IN SUPABASE SQL EDITOR ==="
echo ""

echo "-- STEP 1: Create a test JC (this will auto-create segments)"
echo "INSERT INTO junction_closures (node_id, ofc_cable_id, position_km)"
echo "VALUES ('4d2b0dc9-f63a-4a6d-8fdc-ddb7d44875a7', '117c7353-99a9-4220-8cfd-0669d93b4f4b', 5.0);"
echo ""

echo "-- STEP 2: Check initial segments"
echo "SELECT 'Initial segments:' as status, id, segment_order, start_node_id, end_node_id, distance_km"
echo "FROM cable_segments"
echo "WHERE original_cable_id = '117c7353-99a9-4220-8cfd-0669d93b4f4b'"
echo "ORDER BY segment_order;"
echo ""

echo "-- STEP 3: Delete the JC (this will auto-recreate segments)"
echo "DELETE FROM junction_closures"
echo "WHERE node_id = '4d2b0dc9-f63a-4a6d-8fdc-ddb7d44875a7'"
echo "  AND ofc_cable_id = '117c7353-99a9-4220-8cfd-0669d93b4f4b'"
echo "  AND position_km = 5.0;"
echo ""

echo "-- STEP 4: Check recreated segments"
echo "SELECT 'After deletion:' as status, id, segment_order, start_node_id, end_node_id, distance_km"
echo "FROM cable_segments"
echo "WHERE original_cable_id = '117c7353-99a9-4220-8cfd-0669d93b4f4b'"
echo "ORDER BY segment_order;"
echo ""

echo "-- STEP 5: Check database logs for trigger activity"
echo "SELECT message"
echo "FROM postgres_log"
echo "WHERE message LIKE '%JC deleted%' OR message LIKE '%recreated cable segments%'"
echo "ORDER BY log_time DESC"
echo "LIMIT 10;"
echo ""

echo "=== WHAT SHOULD HAPPEN ==="
echo ""
echo "✅ INSERT JC → Trigger fires → Cable segments created"
echo "✅ DELETE JC → Trigger fires → Cable segments recreated"
echo "✅ Database logs show: 'JC deleted: ... Recreating cable segments.'"
echo "✅ Database logs show: 'Successfully recreated cable segments...'"
echo ""

echo "=== WHAT HAPPENS IN YOUR APP ==="
echo ""
echo "1. User goes to Route Manager"
echo "2. User selects a cable with JCs"
echo "3. User clicks delete on a JC"
echo "4. JcFormModal or delete handler calls DELETE on junction_closures"
echo "5. Database trigger automatically recreates cable segments"
echo "6. UI refreshes and shows updated cable segments"
echo "7. No manual intervention needed!"
echo ""

echo "=== EDGE CASES HANDLED ==="
echo ""
echo "🔸 Delete last JC on cable → All segments deleted, cable becomes single segment"
echo "🔸 Delete middle JC → Segments recreated with remaining JCs"
echo "🔸 Cable not found → Graceful handling, no error"
echo "🔸 Multiple JCs on same cable → All remaining JCs included in recreation"
echo ""

echo "=== DEBUGGING ==="
echo ""
echo "If segments don't update automatically:"
echo "1. Check if triggers are enabled: SELECT * FROM pg_trigger WHERE tgname LIKE '%jc%';"
echo "2. Check database logs: Look for trigger execution messages"
echo "3. Verify function exists: SELECT * FROM pg_proc WHERE proname = 'trigger_recreate_cable_segments_on_jc_delete';"
echo "4. Test trigger manually: SELECT trigger_recreate_cable_segments_on_jc_delete();"
