#!/bin/bash
# Test database connectivity and permissions

echo "=== Database Connectivity Test ==="
echo "Testing if the database connection and permissions are working..."
echo ""

echo "🔍 Check these in browser console:"
echo "1. Open Route Manager"
echo "2. Select a cable"
echo "3. Click 'Add Junction Closure'"
echo "4. Fill form and submit"
echo "5. Look for these logs:"
echo ""

echo "✅ Expected logs:"
echo "   === JcFormModal RENDERED ==="
echo "   === JC FORM SUBMIT DEBUG ==="
echo "   Executing query..."
echo "   Supabase client: {...}"
echo "   Query type: INSERT"
echo "   Payload: {...}"
echo "   Query result: {...}"
echo ""

echo "❌ If you see timeout error:"
echo "   - Database connection issue"
echo "   - Network connectivity problem"
echo "   - Supabase service unavailable"
echo ""

echo "❌ If you see permission error:"
echo "   - Row Level Security (RLS) policies blocking the query"
echo "   - User doesn't have INSERT permission on junction_closures"
echo "   - Database function permissions issue"
echo ""

echo "🔧 Troubleshooting steps:"
echo "1. Check Supabase Dashboard → Authentication → Users"
echo "2. Verify the user has proper permissions"
echo "3. Check Supabase Dashboard → Database → Tables → junction_closures"
echo "4. Check RLS policies for the table"
echo "5. Test with a different user account"
echo ""

echo "📋 Manual database test:"
echo "1. Go to Supabase Dashboard → SQL Editor"
echo "2. Run this query:"
echo "   INSERT INTO junction_closures (node_id, position_km, ofc_cable_id, name)"
echo "   VALUES ('test-jc-id', 1.0, 'your-cable-id', 'Test JC');"
echo "3. If it fails, check permissions"
echo ""

echo "🎯 Most likely issues:"
echo "1. Database connection timeout"
echo "2. RLS policy blocking the insert"
echo "3. Missing permissions on junction_closures table"
echo "4. Network connectivity issues"
